### ISSUE TITLE
Materials

### ISSUE THREAD

**Issue by elvisprivate** [aczwink/KORG-Tools#52]
Hello there! I noticed that you have experience in reversing functions, and I was hoping to reach out to you for some guidance. I spent a whole month reversing the OC31 algorithm and when I finished and had a working decompression algorithm, I found your impressive repository. However, progress has been slow and I was wondering if you could possibly offer me some help by pointing me in the direction of any additional materials or resources that could aid me in my quest. I've tried using the PA600 firmware, but unfortunately, it hasn't been much help. Any assistance you can provide would be greatly appreciated. Thank you for your time and consideration!

**Comment by aczwink** [comment]
Hi elvisprivate,
I think this is some kind of private request and not an issue with the repo. Please consider writing me a e-mail. You can find my address in any of the code files (at the top).
